### ISSUE TITLE
Manual recovery

### ISSUE THREAD

**Issue by fatthomy** [ufb/Textmarker#39]
I would love a function to recover the highlightings manually. I use the Textmarker very much on a login-website using a lot of javascript. Now it often starts the recovering and reports a sucess before I open certain submenus on the website. However, because textmarker reported success earlier I cannot retry the recovery after rendering new text parts.

**Comment by ufb** [comment]
Hi @fatthomy, do you mean that by opening the submenus the page is re-rendering the content and therefore the already successfuly restored highlights vanish?
Last version I added the retry function for a similar case: That a recovery fails, because - after complete loading of the page - content gets rendered with JavaScript.
But for your case it surely makes sense to let the user have the option for a manual recovery.

**Comment by fatthomy** [comment]
Hi @ufb, at first, sorry for my poor explanatory skills, I try to make it a bit clearer: The "successful" restoring does not restore anything actually, maybe the two images below make my case clearer:

![highlighter1](https://user-images.githubusercontent.com/46483778/50828104-b199eb80-1340-11e9-881e-b9b350e5eace.png)
Img1: This is how the website (or better, the relevant content part of it) looks like, when loading it. Now textmarker restores the markings for this kind of "menu" page, although actually there are none...

![highlighter2](https://user-images.githubusercontent.com/46483778/50828353-72b86580-1341-11e9-9c78-7f678eeec0f4.png)
Img2: Here I opened the first content box in the kind of "drop-down menu". In the appearing _Abstract_ text part I actually marked stuff, which now is not recovered and I cannot retry the recovery due to the already "successful" recovery on the same page.

Btw, thanks for your really quick reply!

**Comment by ufb** [comment]
Hm, if Textmarker reports a success, then it acutally did recover all your highlights (even if the corresponding text is not visible). That means, the abstract text was already been rendered - just hidden.
That there are no highlights when you open the dropdown can have different reasons:
Either the page is indeed re-rendering the content (which is very much possible, but also a bit odd, since obviously it was already there before - just not visible. It's also possible that the page re-renders the content as "response" to the insertion of highlights).
Another possibility is that the highlights are still there but not visible - for whatever reason.
It would be great if I could explore myself what is happening there, but you mentioned a log-in, right?
Do you know by chance how to use the browser's built-in developer tools and how to inspect the page content? Or is there some page I can access without having to log-in?

**Comment by fatthomy** [comment]
I know how the "inspect elements" option in Firefox, however I am not skilled in web programming to make much use of the readout.
Yes, it's indeed a login page, however there should be a five day trial: https://www.amboss.com/us/account/login

**Comment by fatthomy** [comment]
Hm, strange that it opens the dropdowns by default, in fact I searched for this option without success for quite some time -.-
Can you switch it off by using the "arrow-down" button in the upper right (or the SPACE-bar as a shortcut)?

**Comment by ufb** [comment]
OK, I have an account now, I opened above page, dropdowns were closed, I opened the abstract, highlighted something, reloaded the page, dropdown was closed and Textmarker reported a recovery-failure. Then I opened the abstract and clicked the retry button in Textmarker's sidebar - and e voilà: The highlight got restored.
Are you sure that Textmarker reports a success in your case even if the dropdown is closed?

**Comment by ufb** [comment]
If you look in Textmarker's history and choose the "Detail List" view (Detail-Liste) -> what does it say how many highlights there are? Lost highlights are still in memory, until you remove them manually. So, maybe Textmarker reports a success because there are 0 non-lost highlights to restore?

**Comment by ufb** [comment]
> Are you currently trying on the German or the US version?  

German. I'm German;)

> it is all stored in the same entry  

That is because it's actually the same site. the hash ending of the URL does not effect requests to the server, it's for client-side only

**Comment by ufb** [comment]
I already deleted my account, since I read in the confirmation mail:

> Mit der Anmeldung bestätigst du, dass du Angehöriger eines Heilberufes im Bereich der Medizin...

**Comment by ufb** [comment]
> However, now Textmarker reports a recovery-success in my case without the option to retry after opening the specific dropdown.

That is really strange. I don't know why it works for me but not for you.
Anyway, I think it'd be a good idea to add a manual retry option even after a success report. I will do that, but I can't promise that I find the time to already add this feature for next release. The upcoming version 4.0.0 will bring a lot of new features and changes. It's almost finished, but there is a lot of testing still to do, so will take some weeks till its release.
Sorry for the inconvenience

**Comment by ufb** [comment]
@fatthomy, I changed the retry option, so that the button will appear after any restoration - even successful ones. Only had to change one line of code. All it does is: Undo all highlights and start over the restoration, so should be perfectly fine as is.
It will be part of next release - approximately by the end of January.
Schönen Abend Dir noch!

**Comment by fatthomy** [comment]
Ok, few things here:

1. > Yes, I just retried the same procedure you described above: I opened above page, dropdowns were closed, I opened the abstract, highlighted something, reloaded the page, dropdown was closed.

To my embarrassment, I have to admit that I simply forgot so save after I tried the above. I turned off the auto-save for testing before...So now this works for me to, just as for you.

2. I stumbled upon the "error" at first, when switching between different sections  of a "days" in the learning library, and this now actually keeps being a problem: I now did this:
Mark something in Abstract section of Chapter A. Move then to the next Chapter B, mark something in the Abstract section there, too. But when toggling back to Chapter A now, the highlightings there are lost. Now, refreshing the page or logging off and on again sometimes helps, sometimes it also just fires a futile "successful" recovery with all dropdowns closed, I will watch this and look for regularities...
Maybe I should try the experimental word-by-word storing I saw in the history?...

3. Anyway thanks for your enthusiast help, I am looking forward for your new update, maybe the manual refresh will do the trick for me already!

Und dir auch nen schönen Abend ;)

**Comment by ufb** [comment]
Hey, a quick note to your second point:
It's bad practice of the site to show different resource representations on the same URI (the hash at the end has no meaning to the server).
Textmarker will only restore a) when the page is fully loaded or b) when you click the retry button. So, suppose you have highlights in chapters A and B and both are closed on page load. By opening A and clicking retry Textmarker will restore the highlights in A but not in B. If there is no way to have both chapters A and B opened at the same time, Textmarker will always treat highlights of the closed chapters as being lost.
I'm going to wrap my head around this and try to come up with some sort of solution - maybe the way to go would be to give the user (you) more control over what happens with "lost" highlights. So, "telling" Textmarker to not give up on lost highlights but try to restore them each time again. In combination with disabling failure notifications this could bring a satisfying result...
Using the experimental word-by-word storing won't be of any help to you, I believe.

**Comment by fatthomy** [comment]
> So, "telling" Textmarker to not give up on lost highlights but try to restore them each time again

Ah, so if I understand you correctly, the way it works right now means that highlights that could not be recovered will be cleared from the history? That would explain, why my history get's empty after a while now...Your idea sounds like a good plan, at least for my case.

>  Using the experimental word-by-word storing won't be of any help to you, I believe.

You seem to be right, this doesn't change much from the user's point of view.

**Comment by ufb** [comment]
No, highlights that could not be recovered won't be cleared, unless you clear them manually (it's one of the selection options on your history page). Textmarker just doesnt try on a later visit to recover those highlights. In most cases this behavior makes sense, but in your case it would actually be ideal if you have control over what happens to highlights that couldn't be recovered.
What do you mean by "history get's empty"? Do you mean whole entries? Or just the highlights of an entry (in case they couldn't be recovered)? A loss of the complete history is possible in case of a Firefox crash, which is out of my reach, and which is why creating backup files frequently is recommended. You can either download a backup file of your complete storage on the "Export / Import" page or for history entries of your choice on the history page.

**Comment by fatthomy** [comment]
> What do you mean by "history get's empty"? Do you mean whole entries? Or just the highlights of an entry (in case they couldn't be recovered)?

Well, after setting quite some highlights yesterday, I checked in today after reading your post above and saw, that the counter was set on "Markierungen: 0":

_Kein Tag zugeordnet
 08.01.2019, 19:36:24 – 09.01.2019, 20:46:07    Markierungen: 0_     

Yesterday it was at least 9 after setting some notes. (Also, it seems odd to me that they all seem to be stored in the same entry, although I chose the option to store each one individually. Or is "Kein Tag zugeordnet" just the collection of all entries, that have no name tag? Oddly, I cannot download the .txt file for this entry, to check if yesterday's markings are indeed lost...

**Comment by ufb** [comment]
> the counter was set on "Markierungen: 0

Ah ok, so it's "only" the highlights - and probably for the reason discussed above.

> all seem to be stored in the same entry, although I chose the option to store each one individually

Textmarker will ignore this option if you have already an entry in your history for that specific URL. Using both for the same page cannot work, so you have to decide for a method - if you choose "1 highlight per entry" then make sure to delete the already existing entry from the history first.

"No tag assigned" or 

> "Kein Tag zugeordnet"

 just means that you haven't made any categorizations of your history entries yet. You have the possibility to attach tags to your entries and filter your entries by tags. This is a feature for users with hundreds or thousands of entries to be able to organize them - similar to a folder system

**Comment by ufb** [comment]
I found the time today to have a closer look at the described szeario and the solution is pretty straightforward and how I already described above:

Just "tell" Textmarker to not give up on non-recoverable highlights.
So, suppose you have a highlight (h1) in chapter A and another one (h2) in chapter B. When you open the page with none of the chapters already being rendered yet on load, Textmarker will fail to restore h1 and h2, showing the failure notification. Then you open A and click the retry button -> Textmarker will restore h1 and - again - show a failure notification, since h2 couldn't be recovered. Then you switch to B, the page re-renders its content and Textmarker will restore h2, again showing a failure notifcation, since h1 was not being recovered.

So, all there is to do is to try restoring all highlights (even the ones that couldn't be restored the last time) on each visit of the page and each retry. I will probably make it the default behavior, giving the user the option to switch off this behavior (beause (s)he needs to have the possiblilty to get rid of non-recoverable highlights).

Note: The user might want to disable those failure notifications (which is already possible under Settings > Notifications)

I will add this settings option to upcoming version 4.0.0.
This version will also enable you to retry the restoration even if Textmarker was able to restore all highlights (see issue #39).

**Comment by ufb** [comment]
done. 4.0.0 still needs to be tested intensively before its release

**Comment by ufb** [comment]
Uploaded 4.0.0 just now.
Go to the settings page, tab "history" and remove checkmark for: "If a highlight wasn't restorable: Don't try again next time"
This will enable you to restore your highlights with the retry button every time the page renders new content (so when you open a different article while the URL stays the same)
Of course this will result in failure notifications, because Textmarker will only restore the highlights of which the corresponding text was rendered - just disable these notifications under settings > notifications, if they disturb you ;)
Hope it works for you

**Comment by fatthomy** [comment]
Hi, first of all thanks for your great effort to help! Unfortunately, my first impression is, that it still does not seem to work properly for me.
I still have to make out all the changes of the update but, first thing I recognize, that Textmarker does not seem to realize, it is on a page, where there are things to restore:
As we worked out, in my case the website has always the same URL, just  text is rendered. However, Textmarker does save the marks I make in different history entries named after the individual chapters.
On restoring however, I noticed now, that the page title now displayed in the side bar does not fit with the actual chapter loaded on the web page. Therefore, Textmarker does not even try to restore anything, so I cannot make him try another time...

Also, when I navigate to the overview of one day showing the individual chapters Textmarker get's stuck with a "restoring markups" window. Unfortunatly it won't succeed with the restoration and if I abort the restoration I cannot start another one manually when navigated to the actual chapter of interest and also I cannot save any marks.

(I hope my report is comprehensible enough ;) )

**Comment by ufb** [comment]
> Textmarker does save the marks I make in different history entries named after the individual chapters.

Sure about that? That would mean that those pages do in fact have different URLs. Which naming method do you use - by page title, by highlighted word or do you choose custom names?

> Textmarker does not seem to realize, it is on a page, where there are things to restore

> when I navigate to the overview of one day showing the individual chapters Textmarker get's stuck with a "restoring markups" window

So do those pages (chapter and overview) have a different URL? Because on one site it's trying to restore, but on the other one not? You can see on which URL you saved the highlights by clicking the small icon next to the entry name on your history page. A detail window will open that is displaying the URL.

Can you also check the error logs page to see if there is an entry that could help figuring out why Textmarker got stuck with restoring? I think there is some misunderstanding on how Textmarker saves your highlights, but that the progressbar-window is getting stuck, that definately is a bug, but I can't fix it without knowing where to look. And unfortunately I cannot recreate this szenario, since I don't have access to this page (login required).

I come back to it tomorrow to see what I can do:)

**Comment by ufb** [comment]
OK, so the URLs have all the same path: "https://www.amboss.com/de/library" but different hashes.
I start at #day=20 and click to article #xid=hK0cTS, then open the abstract and do some highlights,
then from #day=21 I go to article #xid=-f0DK2 and also do some highlights in the abstract.
Then I reload both pages:
a) Failure notification.
b) Then I open the abstract.
c) Then I press the retry button in the Textmarker sidebar and the highlights get restored.
All highlights are saved to the same entry. I chose the naming option "by page title", so the entry's name is "Aufbau der Materie", because that was the title from article #xid=hK0cTS, where I did highlights first.
So, it's working for me, but I do see sometimes that the progressbar-popup won't go away - this is due to some bug, which I have to solve. But in such a case I just reload the page and repeat steps a)-c) and it works.
So sometimes the progress bar crashes (so I reload the page), sometimes not (in which case it works).

It's annoying that all highlights get saved to the same entry. This is because Textmarker is comparing URLs without the hashes. Hashes are meant to be identifiers for a certain part on the same page (an element with that id). But amboss is using those hashes as identifiers for different "pages" - which is bad practice. I won't change Textmarker's behavior concerning hashes, because on a site that is using hashes correctly we wouldn't want different entries for different hashes.
Maybe the way to go would be to have another option in the settings to enable the user to choose how to treat hashes in URLs... I'm not sure, will think about it.

I still don't know what you meant by:

> Textmarker does save the marks I make in different history entries named after the individual chapters

This seems impossible.

**Comment by ufb** [comment]
I found the bug that crashes the restoration - it's because the amboss pages are completely blank on content loaded, then everything gets rendered programmatically. This isn't a problem for Textmarker, just a small code adjustment needed. Will upload the fix today or tomorrow -> 4.0.1
Everything else you reported I wasn't able to retrace - works as expected on those pages.

**Comment by fatthomy** [comment]
> OK, so the URLs have all the same path: "https://www.amboss.com/de/library" but different hashes.
> I start at #day=20 and click to article #xid=hK0cTS, then open the abstract and do some highlights,
> then from #day=21 I go to article #xid=-f0DK2 and also do some highlights in the abstract.
So I did this, too: The first time, entries for both hashes get stored in
  | https://www.amboss.com/de/library#xid=hK0cTS
in the history. Then I refreshed the page on #xid=-f0DK2. Now textmarker is not trying to restore the markings, although the meta data in the side bar show 3 stored markings. Now if I make some more markings, then going back to #xid=hK0cTS and marke something there, too, markings for both chapters get stored with
"Rheumatoide Arthritis (Chronische Polyarthritis)"
 | https://www.amboss.com/de/library#xid=-f0DK2
However the Counter in the meta data sidebar gets "reset" and Textmarker seems to "forget" about the older notations...
Also I checked my history for marks I made during the past weeks. My settings are "store by title", "automatically". And in fact, it seems like Textmarker is saving each hash id as individual page. 
(I added the picture below to illustrate this behavior, on the picture I added some of the hash id's exemplatory in blue, the links are in each case https://www.amboss.com/de/library#_hash-id_ of course.
Now, also you said that that's actually not what textmarker should be doing it would be the ideal behavior for me but unfortunately for some reason, textmarker is not even trying to restore old entries, so I cannot use the change of code you added to try again manually...

Just now I picked for example https://www.amboss.com/de/library#xid=6i0jsf
When the page loads, the side bar shows 3 stored marks in the meta information, but textmarker is not trying to restore them.
Unfortunately, I just cleared my error history to produce some new reports for which I can identify what I did. But right now, I cannot trigger Textmarker to load anything so there are no errors to report. Also I cannot reproduce the stuck loading bar right now... but if I understood you, you figured that out for yourself already?

**Comment by ufb** [comment]
So do you have multiple entries for the same URL but different hashes?

> I added the picture below

Don't see a picture

> you figured that out for yourself already?

Yes, [pushed it already](https://github.com/ufb/Textmarker/commit/085af986acd2e13cc813bbe8189fc88c9a290cc8) - update will be published in the following days (4.0.1)

I have a slight idea about what could have gone wrong with the hashes - will dig into it tomorrow and hopefully come up with a fix that will be added to 4.0.1

Thank you for assisting with hunting down the bugs:)

**Comment by ufb** [comment]
I was not able to reproduce multiple history entries for the same URL.
That Textmarker doesn't try to restore your highlights is most likely because you did not reload the page. When you navigate through the amboss app the hash will change, but hash-changes won't result in a page reload (as explained above: URL hashes are just identifiers for elements on that page - they don't cause a request to the server). Textmarker can detect URL changes (even if it's just a hash change), so I will probably implement an automatic re-restoration of your highlights on such a change. But I won't have enough time by tomorrow - so some time this week;)
Also I'm thinking about a new setting option:
a) new entry on different hash
b) same entry (default)
c) always ask
This way you can take advantage of a), while Textmarker won't mess up other user's histories.

**Comment by fatthomy** [comment]
> That Textmarker doesn't try to restore your highlights is most likely because you did not reload the page.
Actually, I am using the browser's refresh button right after marking a new element (which is stored in the history, I get a message on that). So, in the old version this refresh would trigger a "successful" restoration while all the chapter's text not yet rendered, that's why I suggested the manual recovery button. But now, for some reason, after refreshing the page, Textmarker won't even try to recover...

**Comment by ufb** [comment]
> after refreshing the page, Textmarker won't even try to recover

I can't reproduce this behavior, even after hours of spending with the amboss site.

> I am using the browser's refresh button right after marking a new element

That is actually not neccessary. After navigating to a different chapter (on hash change in the URL) a page refresh or alternatively a click on the retry button is needed to "tell" Textmarker to start the restoration from scratch.
But hopefully all this won't be needed anymore, when I implement above mentioned options this week;)

**Comment by fatthomy** [comment]
Ok, I am waiting hopefully for the update! ;)

**Comment by ufb** [comment]
Hey, I know you are waiting for this update, but I've decided to publish 4.0.1 with the fix for custom markers first - it's an easy fix and urgent for the majority of users - and do the hash option thing a few days later, because there is a lot to consider when implementing it.

**Comment by fatthomy** [comment]
Ok, I just realized another thing. After clearing my history, textmarker is now again restoring markups on the website. However, I cannot find the newly added manual recovery button in the sidebar? Shouldn't it be there automatically even after "successful" recovery?

**Comment by ufb** [comment]
> I cannot find the newly added manual recovery button in the sidebar?

![retry](https://user-images.githubusercontent.com/17272252/53181209-0cd12600-35ef-11e9-833e-307148ec00bf.jpg)

> Shouldn't it be there automatically even after "successful" recovery?

Yes

> Is the synchronizing of history supposed to work? Seemingly I cannot import other entries from another device...

This depends on if you have a sync account with Firefox. If by "import" you mean the import button on Textmarker's "Export & Import" page, then you confuse import with syncing. The import is for backup files that you have been exported before;)

**Comment by ufb** [comment]
Published 4.1.0 just now.
The code to this issue is mostly with this [commit](https://github.com/ufb/Textmarker/commit/154b55abc9a122b8e5a40c5abb075cea0ff87598)

You now have the option to enable storing highlights on the same page but different hashes in the URL in separate history entries.
![hashsensitive](https://user-images.githubusercontent.com/17272252/53532702-d2382380-3aef-11e9-8291-82f5282eb9e0.jpg)

Make sure to not use this setting enabled for `someurl#hash` and disabled for `someurl#differenthash` - this might result in conflicts.
Also note that Textmarker will redo the whole restoration process for a page in case the following are true:
- the URL hash changed (being on the same page)
- the corresponding entry (if there is one) is saved as `hashSensitive` (the above setting was enabled when the entry was being created)

Please also note that this feature is experimental; I did a lot of testing, but I'm the only one doing that and there is just not enough time - in case you encounter unexpected behavior, please let me know :)

And a last note:
4.1.0 forces the following setting to be enabled:
![noretry](https://user-images.githubusercontent.com/17272252/53532989-f1838080-3af0-11e9-87c8-3cc98d890ec7.jpg)
This is because I set `disabled` as the default for new users - which was the wrong way to go, because this is an advanced setting that needs to be used with caution.
Just disable it again, if you wish ;)

**Comment by fatthomy** [comment]
Hi, sorry for the long delay, I took a few days off. So, now I cleared my history to test the new hashsensitive option which would be ideal for my case I guess.
However, I still have some trouble. As I reported before, I observe some odd behavior right now: 
1) I ticked the hashsensitive option and "store by website title" However, after marking to words, I get one history entry with the first word marked and another one with both words marked. I cannot explain this behavior, can you?
2) After reloading the page, textmarker makes no effort to restore the markings. Also, as I noted before, there is no manual recovery button since textmarker does not seem to notice that there is anything to recover...

**Comment by ufb** [comment]
Das scheint mir ein sehr spezieller Fall zu sein, macht's Dir was aus, wenn wir das auf die E-Mail-Ebene verschieben? Im Idealfall könntest du mir die beiden Einträge als Backup-Files schicken, dann könnt ich den Fall ganz einfach reproduzieren. Aber da ist ja das Problem, dass ich keinen Zugriff auf besagte Seiten hab..

**Comment by fatthomy** [comment]
Alles klar, hab's dir eben gemailt.
